# Generated by Django 5.0.1 on 2024-05-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_link',
            field=models.URLField(max_length=900),
        ),
    ]
