# Generated by Django 5.0.3 on 2024-05-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_google_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
