# Generated by Django 5.0.3 on 2024-06-06 21:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.CharField(default=core.models.generate_feedback_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=1500)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
