# Generated by Django 5.0.3 on 2024-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
