# Generated by Django 5.0.3 on 2024-05-25 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=256)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('page_visited', models.CharField(max_length=256)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=40)),
            ],
        ),
    ]
