"""
Django settings for ebook project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import environ
import dj_database_url
import psycopg2

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lbdqe-r26a87u!is#s#%aa-+e+tt4$kwdqs@!&om0^4-fyjd)j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    'uniflex.onrender.com',
    'www.uniabujaflex.com.ng',
    'localhost',
    '127.0.0.1',  # Loopback address for local development
    '0.0.0.0'     # Optional: Allow binding to all interfaces for local development
    'uniflex-production.up.railway.app'
]


# ALLOWED_HOSTS = []



# Initialize environment variables
# env = environ.Env()
# environ.Env.read_env()  # Read .env file

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Other settings...


# Other settings...



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    # 'django_seo_js',
    'library',
    'core',
    'location',
    'user', 
    'site_analsys',
    # 'seo'
    
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #more middelware
    'django.middleware.security.SecurityMiddleware',
    'site_analsys.middleware.VisitorTrackingMiddleware',
    
    
]

ROOT_URLCONF = 'ebook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

WSGI_APPLICATION = 'ebook.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME':  'db.sqlite3',
#     }
# }





# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'your_database_name',
#         'USER': 'your_database_user',
#         'PASSWORD': 'your_database_password',
#         'HOST': 'your_database_host',  # Set to 'localhost' if the database is on the same machine
#         'PORT': 'uniabujafle.cpgu0ygiudke.eu-north-1.rds.amazonaws.com',  # Set to '' for default
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# CSRF_TRUSTED_ORIGINS = [
#     "www.uniabujaflex.com.ng",
# ]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'


USE_I18N = True

USE_TZ = True


AWS_ACCESS_KEY_ID = "AKIA5DILOY5YYEAUKIN3"

AWS_SECRET_ACCESS_KEY = "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"

AWS_STORAGE_BUCKET_NAME = "uniabujaflex"

AWS_S3_FILE_OVERWRITE = False

AWS_DEFAULT_ACL = None

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

AWS_LOCATION = 'static'

STATIC_LOCATION = 'static'

STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'





LOGIN_URL = "user:sign-in"

LOGOUT_REDIRECT_URL = "user:sign-in"

AUTH_USER_MODEL = 'user.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    # "site_title": "MovieX",
    "site_header": "UniabujaFlex",
    "site_brand": "learning Made Easy...",
    # "site_logo": "images/logo.jpg",
    "copyright": "UniabujaFlex - All RIght Reserverd © Copyright 2023",
    # "order_with_respect_to": ["core", 'userauths', "transactions" , 'addon', 'blog']

    
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-olive",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cyborg",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    # New tweaks added below
    "sidebar_nav_icons": True,
    "sidebar_nav_flat": False,
    "sidebar_nav_legacy": False,
    "sidebar_nav_child_arrows": True,
    "sidebar_nav_labels": False,
    "sidebar_nav_indicators": True,
    "sidebar_nav_hover_expand": False,
    "sidebar_nav_light": False,
    "sidebar_nav_flat_hover": False,
    "sidebar_nav_legacy_hover": False,
    "sidebar_nav_child_indent_hover": False,
    "sidebar_nav_compact": False,
    "sidebar_nav_legacy_active": False,
    "sidebar_nav_legacy_fixed": False,
    "sidebar_nav_child_indent_active": False,
    "sidebar_nav_compact_hover": False,
    "sidebar_nav_legacy_hover_expand": False,
    "sidebar_nav_child_indent_hover_expand": False,
    "sidebar_nav_compact_hover_expand": False,
    "sidebar_nav_labels_hover_expand": False,
    "sidebar_nav_indicators_hover_expand": False,
    "sidebar_nav_active_bold": False,
    "sidebar_nav_active_italic": False,
    "sidebar_nav_active_light": False,
    "sidebar_nav_active_underline": False,
    "sidebar_nav_active_uppercase": False,
    "sidebar_nav_active_small_caps": False,
    "sidebar_nav_active_strikethrough": False,
    "sidebar_nav_active_text_sm": False,
    "sidebar_nav_active_text_xs": False,
    "sidebar_nav_active_text_xxs": False,
    "sidebar_nav_hover_bold": False,
    "sidebar_nav_hover_italic": False,
    "sidebar_nav_hover_light": False,
    "sidebar_nav_hover_underline": False,
    "sidebar_nav_hover_uppercase": False,
    "sidebar_nav_hover_small_caps": False,
    "sidebar_nav_hover_strikethrough": False,
    "sidebar_nav_hover_text_sm": False,
    "sidebar_nav_hover_text_xs": False,
    "sidebar_nav_hover_text_xxs": False,
    
        # New icon-related tweaks added below
    "sidebar_nav_icons": True,  # Enable sidebar navigation icons
    "sidebar_nav_icon_size": "sm",  # Set sidebar navigation icon size to small
    "sidebar_nav_icon_spacing": True,  # Add spacing between sidebar navigation icons and text
    "sidebar_nav_icon_color": "text-dark",  # Set sidebar navigation icon color to dark text color
    "sidebar_nav_icon_active_color": "text-primary",  # Set active sidebar navigation icon color to primary color

    # Additional icon tweaks for specific navigation items
    "sidebar_nav_icons_custom": {
        "dashboard": "fas fa-tachometer-alt",  # Custom icon for the dashboard navigation item
        "profile": "fas fa-user",  # Custom icon for the profile navigation item
        "settings": "fas fa-cog"
    }
}
