"""
Django settings for ebook project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Reading .env file
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    'uniflex.onrender.com',
    'www.uniabujaflex.com.ng',
    'uniabujaflex.com.ng',
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    'uniflex-production.up.railway.app',
    'registry.npmjs.org'
])

# Security settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'library',
    'core',
    'location',
    'user',
    'site_analsys',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'site_analsys.middleware.VisitorTrackingMiddleware',
]

ROOT_URLCONF = 'ebook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ebook.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.config(conn_max_age=600)
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Django storages settings
DEFAULT_FILE_STORAGE = 'storages.backends.ossboto3.OSSBoto3Storage'
AWS_S3_REGION_NAME = 'oss-us-west-1.aliyuncs.com'
AWS_S3_ENDPOINT_URL = 'https://' + env('OSS_ENDPOINT')

# Media and static files settings
MEDIA_URL = 'https://' + env('OSS_BUCKET_NAME') + '.' + env('OSS_ENDPOINT') + '/'
STATIC_URL = 'https://' + env('OSS_BUCKET_NAME') + '.' + env('OSS_ENDPOINT') + '/'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

CSRF_TRUSTED_ORIGINS = [
    'https://www.uniabujaflex.com.ng',
    'https://uniabujaflex.com.ng',
    'https://uniflex.onrender.com',
    'https://uniflex-production.up.railway.app',
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Lagos'
USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_header": "UniabujaFlex",
    "site_brand": "learning Made Easy...",
    "copyright": "UniabujaFlex - All Rights Reserved © Copyright 2023",
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-indigo navbar-dark",
    "sidebar": "sidebar-dark-indigo",
    "theme": "cyborg",
    "dark_mode_theme": "cyborg",
}

LOGIN_URL = "user:sign-in"
LOGOUT_REDIRECT_URL = "user:sign-in"
AUTH_USER_MODEL = 'user.User'
